#!/bin/bash

d=$(date +%Y%m%d%H%M%S)

if [ "$1" == "--help" ]; then
    echo "USAGE: $0 [PLATFORM]"
    echo "PLATFORM is either linux/arm64 or linux/amd64"
    exit 1
fi

if [ -z "$1"  ]; then
    platform="linux/amd64"
else
    platform="$1"
fi

platform_tag=$(echo $platform | sed 's|/|-|g')
TAG_base="skogsbaer/compiler-construction-wasm_${platform_tag}"
TAG1=${TAG_base}:latest
TAG2=${TAG_base}:$d

echo "Building for platform $platform"
echo "Tags: $TAG1 and $TAG2 ..."

cd $(dirname $0)/..
docker build --platform "$platform" --tag $TAG1 --tag $TAG2 --file docker/Dockerfile . || exit 1

echo "Building done, now pushing ..."
echo "Tags: $TAG1 and $TAG2 ..."

docker push $TAG1
docker push $TAG2
