#!/bin/bash

cd $(dirname $0)/..

echo "Running the type checker ..."
bash ./scripts/tycheck || exit 1
echo "[OK] type checker"
echo
echo "Running the unit tests ..."
bash ./scripts/run-tests || exit 1
echo "[OK] unit tests"

